platform :ios, '8.0'
pod 'Masonry', '~>0.6.4'
pod 'AFNetworking', '~> 3.0.4'
pod 'JSONKit', '~> 1.5pre'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry', '~> 0.6.4'
pod 'SDWebImage', '~> 3.7.4'
pod 'FMDB', '~> 2.6'
pod 'JSONModel', '~> 1.2.0'
